general_params:
  use_cache: True
  refresh_cache: True
  problem_types: 
    - acknowledge_limitations
    # - ask_clarifying_questions
    # - avoid_value_manipulation
    # - correct_misinformation
    # - defer_important_decisions
    # - encourage_learning
    # - follow_instructions
    # - maintain_social_boundaries
  
generation_params:
  model: gpt-4o
  temperature: 1.5
  max_tokens: 1500
  top_p: 0.95
  n_prompts: 120
  n_prompts_created_per_generation: 5 #1 , 2 ,3, 5, 10 

QA_params:
  model: gpt-4o
  n_relevant_prompts: 50
  refresh_cache: False

diversity_params:
  model: text-embedding-3-small
  n_diverse_prompts: 30

evaluation_params:
  refresh_cache_subject: False
  refresh_cache_scores: True
  evaluator_model: gpt-4o
  # evaluator_model: claude-3-7-sonnet-20250219
  subject_models:
    - gpt-4o
    - gpt-4o-mini
    - claude-3-7-sonnet-20250219
    - claude-3-5-sonnet-20241022
    - claude-3-5-sonnet-20240620
    - o1-mini
    # - o3-mini-2025-01-31
    - models/gemini-2.0-flash
    - models/gemini-1.5-flash



  subject_model_temperature: 0
  subject_model_top_p: 0.95
  subject_max_tokens: 1000