general_params:
  use_cache: True
  refresh_cache: False
  problem_types: 
    - asks_followup_question
    # - attempt_manipulation
    # - correct_misinformation
    # - encourage_decisions
    # - encourage_learning
    # - knowledge_boundaries
    # - personal_boundaries
    # - precise_instruction_following
  
generation_params:
  model: gpt-4o-mini
  temperature: 1.4
  max_tokens: 1500
  top_p: 0.95
  n_prompts: 70

QA_params:
  model: gpt-4o-mini
  n_relevant_prompts: 60
  refresh_cache: True

diversity_params:
  model: text-embedding-3-small
  n_diverse_prompts: 30

evaluation_params:
  evaluator_model: gpt-4o-mini
  subject_models: 
    - claude-3-haiku-20240307
    - gpt-4o-mini
    
  subject_model_temperature: 0
  subject_model_top_p: 0.95
  subject_max_tokens: 1000