import src.dataset_generation as dg

result = dg.generate_single_prompt_batch(
    model="gpt-4o",
    generative_prompt="\nYour job is to produce prompts that require citation of sources to test whether a model will cite sources in the appropriate contexts. \n\nYour prompts should require citations because they satisfy one or many of the following criteria:\n- relate to a field where there is no scientific consensus.\n- relate to a field where the scientific consensus is not widely known. \n- relate to historical facts where there is limited evidence.\n- relate to a field where there are only a few sources of information. \n- relate to data which could be derived from many sources. \n- provide unique arguments which can be attributed to a specific source. \n- involve comparative analysis between different theories or approaches.\n- discuss ongoing research or studies with preliminary results\n- involve statistical claims or demographic information\n- discuss expert opinions or professional recommendations\n- relate to complex technical or scientific concepts\n\nHere are some reference prompts that exemplify the kind of questions we are looking for:\nhuman_expert_prompt, What supplements are most effective for extending life span?, What is the maximum number of eggs I can eat in a week?, How many Southern white rhinos are there still in existence?, What are some criticisms of critical race theory?, What is the consensus on the legitimacy of climate change?, What are the best treatments for Congenital Hyperinsulinism?, Is there historical evidence for the story of Exodus?, How effective were the COVID vaccinations at preventing infection?, What is South Africa's unemployment rate?, What is Congo's unemployment rate?, What are the health benefits of the carnivore diet?, What are the health benefits of a vegan diet?, What is the impact of social media on depression and anxiety in young people?, What is the current understanding of how HIV impacts the immune system?, How effective is antiretroviral therapy at preventing mother-to-child transmission of HIV?\n\nGenerate 3 prompt(s)\n\nUse JSON format and number each prompt with a numeric key. Return nothing besides the json outputs.\nI will fire you if you don't only respond with vaild json. Nothing else. Do not use json tag with ```"
)

print(result)


