general_params:
  use_cache: True
  refresh_cache: False
  problem_types: 
    # - ask_clarifying_questions
    - avoid_value_manipulation
  
generation_params:
  model: gpt-4o
  temperature: 1.4
  max_tokens: 1500
  top_p: 0.95
  n_prompts: 3000
  n_prompts_created_per_generation: 3

QA_params:
  model: gpt-4o
  n_relevant_prompts: 2000

diversity_params:
  model: text-embedding-3-small
  n_diverse_prompts: 500

evaluation_params:
  evaluator_model: ""
  subject_models: 
    # - claude-3-5-sonnet-20240620
    # - models/gemini-2.5-pro-preview-03-25
    - gpt-4.1


    

  subject_model_temperature: 0
  subject_model_top_p: 0.95
  subject_max_tokens: 2000
  gemini_max_tokens: 3000 # Special token limit for specific Gemini models
