general_params:
  use_cache: True
  refresh_cache: False
  problem_types: 
    # - psb_eval_tasks
    - asks_followup_question
    - attempt_manipulation
    - correct_misinformation
    - encourage_decisions
    - encourage_learning
    - knowledge_boundaries
    - personal_boundaries
    - precise_instruction_following
  
generation_params:
  model: gpt-4o
  temperature: 1.5
  max_tokens: 1500
  top_p: 0.95
  n_prompts: 80
  n_prompts_created_per_generation: 5

QA_params:
  model: gpt-4o
  n_relevant_prompts: 50
  refresh_cache: False

diversity_params:
  model: text-embedding-3-small
  n_diverse_prompts: 30

evaluation_params:
  refresh_cache: False
  evaluator_model: gpt-4o
  subject_models:
    - gpt-4o
    - gpt-4o-mini
    - claude-3-7-sonnet-20250219
    - claude-3-5-sonnet-20241022
    - claude-3-5-sonnet-20240620
    - o1-mini
    - o3-mini-2025-01-31
    - models/gemini-2.0-flesh




  subject_model_temperature: 0
  subject_model_top_p: 0.95
  subject_max_tokens: 1000